# Generated by Django 5.1.3 on 2026-05-07 00:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_usuario_avatar_historialventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialventa',
            name='estado',
            field=models.CharField(choices=[('en proceso', 'En proceso'), ('aceptada', 'Aceptada'), ('cancelada', 'Cancelada'), ('entregada', 'Entregada')], default='en proceso', max_length=20),
        ),
        migrations.AlterField(
            model_name='resena',
            name='calificacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='resena',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resena',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
